# Generated by Django 3.2.15 on 2022-09-15 11:00

from django.db import migrations, models
import rrap.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Your name')),
                ('bio', models.CharField(blank=True, max_length=300, verbose_name='Your name')),
                ('avatar', models.ImageField(blank=True, upload_to=rrap.users.models.get_avatar_full_path)),
                ('avatar_version', models.IntegerField(blank=True, default=0, editable=False)),
                ('last_login', models.DateTimeField(db_index=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, max_length=255)),
                ('has_finished_registration', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
