# Generated by Django 3.2.15 on 2023-03-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_other_pronouns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='why',
            field=models.TextField(blank=True, max_length=300, verbose_name='Why are you here?'),
        ),
    ]
