# Generated by Django 3.2.15 on 2023-03-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230303_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='review_status',
            field=models.SmallIntegerField(choices=[(0, 'Pending Review'), (1, 'Approved'), (2, 'Rejected')], default=0, verbose_name='Review status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='why',
            field=models.TextField(blank=True, max_length=500, verbose_name='Why are you here?'),
        ),
    ]
