# Generated by Django 3.2.15 on 2023-03-03 18:49

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0034_pwuidscommunityreach'),
        ('users', '0005_auto_20230303_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Data User', 'verbose_name_plural': 'Data Users'},
        ),
        migrations.AddField(
            model_name='profile',
            name='affiliated_ukpc',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_affiliation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Affiliation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='organisations',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='data_users', to='organizations.OrganisationPage', verbose_name='Which UKPC organisation are you affiliated to? (choose all that apply)'),
        ),
    ]
