# Generated by Django 3.2.15 on 2023-03-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0034_pwuidscommunityreach'),
        ('users', '0006_auto_20230303_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organisations',
            field=models.ManyToManyField(blank=True, related_name='data_users', to='organizations.OrganisationPage', verbose_name='Which UKPC organisation are you affiliated to? (choose all that apply)'),
        ),
    ]
