# Generated by Django 3.2.15 on 2023-03-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organisations',
        ),
    ]
