# Generated by Django 3.2.15 on 2023-03-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0034_pwuidscommunityreach'),
        ('users', '0009_remove_profile_organisations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='affiliated_ukpc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organisationpage', verbose_name='Select UKPC organisation'),
        ),
    ]
