# Generated by Django 3.2.15 on 2023-03-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230303_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='affiliated_ukpc',
            field=models.BooleanField(default=True),
        ),
    ]
