# Generated by Django 3.2.15 on 2023-03-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_affiliated_ukpc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='affiliated_ukpc',
            field=models.BooleanField(default=True, verbose_name='Is the organisation you are affiliated to a member of UKPC?'),
        ),
    ]
