# Generated by Django 3.2.15 on 2023-03-04 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0034_pwuidscommunityreach'),
        ('users', '0013_remove_profile_affiliated_ukpc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organisationpage', verbose_name='Select UKPC organisation'),
        ),
    ]
