# Generated by Django 3.2.15 on 2023-03-05 09:56

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=django_fsm.FSMField(default='requested', editable=False, max_length=50),
        ),
    ]
