# Generated by Django 3.2.15 on 2023-03-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_profile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='review_status',
            field=models.SmallIntegerField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default=0, verbose_name='Review status'),
        ),
    ]
