# Generated by Django 3.2.15 on 2023-03-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_profile_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default=0, max_length=10, verbose_name='Review status'),
        ),
    ]
