# Generated by Django 3.2.15 on 2023-03-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20230307_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Review status'),
        ),
    ]
