# Generated by Django 3.2.15 on 2023-03-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_profile_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_login',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_datauser',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
