# Generated by Django 3.2.15 on 2023-01-03 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0026_auto_20230103_1220'),
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='organization',
        ),
        migrations.AddField(
            model_name='activity',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organisationpage', verbose_name='organisation'),
        ),
    ]
