# Generated by Django 3.2.15 on 2022-11-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homepage_standardpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
    ]
