# Generated by Django 3.2.15 on 2022-11-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_issues_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypopulation',
            name='acronym',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
