# Generated by Django 3.2.15 on 2022-11-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_keypopulation_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
