# Generated by Django 3.2.15 on 2022-11-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221128_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='summary',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='summary',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
