# Generated by Django 3.2.15 on 2022-11-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20221128_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='icon',
            field=models.CharField(blank=True, help_text='Enter name of icon', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(blank=True, help_text='Describe the issue', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(help_text='Name/title of issue', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='Enter name of icon', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='summary',
            field=models.CharField(blank=True, help_text='Describe the service', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(help_text='Name/title of service', max_length=100),
        ),
    ]
