# Generated by Django 3.2.15 on 2022-12-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221130_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name/title of issue', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Describe the issue', max_length=240, null=True)),
            ],
            options={
                'verbose_name': 'Violation',
                'verbose_name_plural': 'Violation',
            },
        ),
    ]
