# Generated by Django 3.2.15 on 2022-12-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_violations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Violations',
            new_name='Violation',
        ),
    ]
