# Generated by Django 3.2.15 on 2022-12-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_violations_violation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='description',
            field=models.CharField(blank=True, help_text='Brief description', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='violation',
            name='title',
            field=models.CharField(help_text='Name of violation', max_length=100),
        ),
    ]
