# Generated by Django 3.2.15 on 2022-12-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20221212_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='violation',
            options={'verbose_name': 'Violation', 'verbose_name_plural': 'Violations'},
        ),
    ]
