# Generated by Django 3.2.15 on 2022-12-21 11:26

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_violation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='color',
            field=wagtail_color_panel.fields.ColorField(default='#000000', max_length=7, null=True),
        ),
    ]
