# Generated by Django 3.2.15 on 2022-12-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_mappage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Publication type',
                'verbose_name_plural': 'Publication types',
            },
        ),
    ]
