# Generated by Django 3.2.15 on 2022-12-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_previewabledocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreviewableDocument',
        ),
    ]
