# Generated by Django 3.2.15 on 2022-12-30 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20221230_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationpage',
            options={'ordering': ['title', 'date_published'], 'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='This is the date shown publicly as the date of publishing. Only month and year will be shown though', verbose_name='Date of publishing'),
        ),
    ]
