# Generated by Django 3.2.15 on 2023-03-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_contactpage_formfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpage',
            name='cta_link',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='video_id',
        ),
    ]
