# Generated by Django 3.2.15 on 2023-03-02 11:25

from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20230301_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWKeyPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color', wagtail_color_panel.fields.ColorField(default='#000000', max_length=7)),
            ],
            options={
                'verbose_name': 'SW Key Population',
                'verbose_name_plural': 'SW Key Populations',
            },
        ),
        migrations.CreateModel(
            name='SWService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name/title of service', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Enter name of icon', max_length=20, null=True)),
                ('summary', models.CharField(blank=True, help_text='Describe the service', max_length=240, null=True)),
            ],
            options={
                'verbose_name': 'SW Service',
                'verbose_name_plural': 'SW Services',
            },
        ),
        migrations.CreateModel(
            name='SWViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of violation', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Brief description', max_length=240, null=True)),
                ('color', wagtail_color_panel.fields.ColorField(default='#000000', max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'SW Violation',
                'verbose_name_plural': 'SW Violations',
            },
        ),
    ]
