# Generated by Django 3.2.15 on 2023-03-02 11:44

from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_swkeypopulation_swservice_swviolation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWUIDService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name/title of service', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Enter name of icon', max_length=20, null=True)),
                ('summary', models.CharField(blank=True, help_text='Describe the service', max_length=240, null=True)),
            ],
            options={
                'verbose_name': 'PWUID Service',
                'verbose_name_plural': 'PWUID Services',
            },
        ),
        migrations.CreateModel(
            name='PWUIDViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of violation', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Brief description', max_length=240, null=True)),
                ('color', wagtail_color_panel.fields.ColorField(default='#000000', max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'PWUID Violation',
                'verbose_name_plural': 'PWUID Violations',
            },
        ),
    ]
