# Generated by Django 3.2.15 on 2023-03-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_pwuidservice_pwuidviolation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
