# Generated by Django 3.2.15 on 2023-03-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20230302_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
    ]
