# Generated by Django 3.2.15 on 2023-03-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_location_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGBTQKeyPopulation',
            fields=[
                ('keypopulation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.keypopulation')),
            ],
            options={
                'verbose_name': 'LGBTQ Key Population',
                'verbose_name_plural': 'LGBTQ Key Populations',
            },
            bases=('core.keypopulation',),
        ),
        migrations.CreateModel(
            name='LGBTQService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.service')),
            ],
            options={
                'verbose_name': 'LGBTQ Service',
                'verbose_name_plural': 'LGBTQ Services',
            },
            bases=('core.service',),
        ),
        migrations.CreateModel(
            name='LGBTQViolation',
            fields=[
                ('violation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.violation')),
            ],
            options={
                'verbose_name': 'LGBTQ Violation',
                'verbose_name_plural': 'LGBTQ Violations',
            },
            bases=('core.violation',),
        ),
        migrations.AlterModelOptions(
            name='keypopulation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='pwuidservice',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='pwuidservice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pwuidservice',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='pwuidservice',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pwuidviolation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='pwuidviolation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pwuidviolation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='swkeypopulation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='swkeypopulation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='swkeypopulation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='swservice',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='swservice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='swservice',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='swservice',
            name='title',
        ),
        migrations.RemoveField(
            model_name='swviolation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='swviolation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='swviolation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='swviolation',
            name='title',
        ),
        migrations.AddField(
            model_name='pwuidservice',
            name='service_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swkeypopulation',
            name='keypopulation_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.keypopulation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swservice',
            name='service_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swviolation',
            name='violation_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.violation'),
            preserve_default=False,
        ),
    ]
