# Generated by Django 3.2.15 on 2022-09-16 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name_plural': 'organisations'},
        ),
        migrations.AddField(
            model_name='organization',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='last update'),
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.user', verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('name', 'owner')},
        ),
        migrations.DeleteModel(
            name='OrganizationPermission',
        ),
    ]
