# Generated by Django 3.2.15 on 2022-11-26 13:33

from django.db import migrations, models
import django.db.models.deletion
import rrap.organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('core', '0002_homepage_standardpage'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('acronym', models.CharField(blank=True, max_length=10, null=True)),
                ('about', models.TextField(blank=True, max_length=400, null=True)),
                ('logo', models.ImageField(blank=True, upload_to=rrap.organizations.models.get_logo_full_path)),
                ('logo_version', models.IntegerField(blank=True, default=0, editable=False)),
                ('website', models.URLField(blank=True, null=True)),
                ('org_type', models.CharField(blank=True, choices=[('individual', 'Individual'), ('donor', 'Donor'), ('government', 'Government'), ('int_ngo', 'International NGO'), ('cso', 'Civil Society Organization'), ('private_sector', 'Private sector'), ('religious', 'Religious'), ('other', 'Other')], max_length=20, verbose_name='Type of organization')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (0, 'Not verified'), (3, 'Disabled'), (4, 'Suspended')], default=0)),
                ('locations', models.ManyToManyField(related_name='organisations', to='core.Location')),
            ],
            options={
                'verbose_name_plural': 'institutions',
            },
            bases=('wagtailcore.page',),
        ),
    ]
