# Generated by Django 3.2.15 on 2022-09-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20220916_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(blank=True, choices=[('academic', 'Academic/Research'), ('donor', 'Donor'), ('government', 'Government'), ('int_ngo', 'International NGO'), ('int_org', 'International organization'), ('national_org', 'National organization'), ('private_sector', 'Private sector'), ('religious', 'Religious'), ('other', 'Other')], help_text='Type of organization', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (0, 'Not verified'), (3, 'Disabled'), (4, 'Suspended')], default=0),
        ),
    ]
