# Generated by Django 3.2.15 on 2022-11-26 13:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('core', '0002_homepage_standardpage'),
        ('organizations', '0003_organisation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organisation',
            new_name='OrganisationPage',
        ),
        migrations.AlterModelOptions(
            name='organisationpage',
            options={'verbose_name_plural': 'organisations'},
        ),
    ]
