# Generated by Django 3.2.15 on 2022-11-26 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221126_2208'),
        ('organizations', '0005_auto_20221126_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationpage',
            name='locations',
        ),
        migrations.AddField(
            model_name='organisationpage',
            name='locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
    ]
