# Generated by Django 3.2.15 on 2022-09-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organization_org_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='removed',
        ),
    ]
