# Generated by Django 3.2.15 on 2022-09-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_topic'),
        ('organizations', '0006_remove_organization_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='locations',
            field=models.ManyToManyField(related_name='organizations', to='core.Location'),
        ),
    ]
