# Generated by Django 3.2.15 on 2022-09-26 21:20

from django.db import migrations, models
import rrap.organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_organization_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_version',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, upload_to=rrap.organizations.models.get_logo_full_path),
        ),
    ]
