# Generated by Django 3.2.15 on 2022-11-26 19:53

from django.db import migrations, models
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221126_2208'),
        ('organizations', '0007_auto_20221126_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationpage',
            options={'verbose_name': 'Organisation', 'verbose_name_plural': 'Organisations'},
        ),
        migrations.AddField(
            model_name='organisationpage',
            name='address',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Office address', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organisationpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='organisationpage',
            name='facebook',
            field=models.URLField(blank=True, help_text='Your Facebook page URL', null=True),
        ),
        migrations.AddField(
            model_name='organisationpage',
            name='instagram',
            field=models.URLField(blank=True, help_text='Your instagram URL', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organisationpage',
            name='medium',
            field=models.URLField(blank=True, help_text='Your medium page URL', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organisationpage',
            name='phone',
            field=models.CharField(blank=True, help_text='Telephone number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='organisationpage',
            name='topics',
            field=modelcluster.fields.ParentalManyToManyField(related_name='organisations', to='core.Topic'),
        ),
        migrations.AddField(
            model_name='organisationpage',
            name='twitter',
            field=models.URLField(blank=True, help_text='Your twitter URL', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organisationpage',
            name='youtube',
            field=models.URLField(blank=True, help_text='Your YouTube channel or user account URL', null=True),
        ),
        migrations.AlterField(
            model_name='organisationpage',
            name='locations',
            field=modelcluster.fields.ParentalManyToManyField(related_name='organisations', to='core.Location'),
        ),
    ]
