# Generated by Django 3.2.15 on 2022-10-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20220927_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('donor', 'Donor'), ('government', 'Government'), ('int_ngo', 'International NGO'), ('cso', 'Civil Society Organization'), ('private_sector', 'Private sector'), ('religious', 'Religious'), ('other', 'Other')], max_length=20, verbose_name='Type of organization'),
        ),
    ]
