# Generated by Django 3.2.15 on 2022-11-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20221127_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationpage',
            name='toll_free',
            field=models.CharField(blank=True, help_text='Toll-free number', max_length=20, null=True),
        ),
    ]
