# Generated by Django 3.2.15 on 2022-11-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_organisationpage_toll_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationpage',
            name='summary',
            field=models.TextField(blank=True, help_text='Describe organisation in one sentence.', max_length=240, null=True),
        ),
    ]
