# Generated by Django 3.2.15 on 2022-12-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_organisationpage_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationpage',
            name='educators',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='organisationpage',
            name='paralegals',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='organisationpage',
            name='village_teams',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='organisationpage',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (0, 'Not verified'), (3, 'Disabled'), (4, 'Suspended')], default=1),
        ),
    ]
