# Generated by Django 3.2.15 on 2022-12-12 17:15

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_violations_violation'),
        ('organizations', '0012_auto_20221212_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolenceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('occurences', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('period', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='organizations.organisationpage')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.violation')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
