# Generated by Django 3.2.15 on 2022-12-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_violenceentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violenceentry',
            name='period',
        ),
        migrations.AddField(
            model_name='violenceentry',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='violenceentry',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
