# Generated by Django 3.2.15 on 2022-12-15 13:19

import django.core.validators
from django.db import migrations, models
import rrap.organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_communityreach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityreach',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='communityreach',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='violenceentry',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='violenceentry',
            name='start_date',
        ),
        migrations.AddField(
            model_name='communityreach',
            name='period',
            field=models.PositiveSmallIntegerField(blank=True, default=2022, null=True, validators=[django.core.validators.MinValueValidator(2000), rrap.organizations.models.max_value_current_year]),
        ),
        migrations.AddField(
            model_name='violenceentry',
            name='period',
            field=models.PositiveSmallIntegerField(blank=True, default=2022, null=True, validators=[django.core.validators.MinValueValidator(2000), rrap.organizations.models.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='organisationpage',
            name='educators',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Peer Educators'),
        ),
        migrations.AlterField(
            model_name='organisationpage',
            name='village_teams',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Village health teams'),
        ),
    ]
