# Generated by Django 3.2.15 on 2022-12-28 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('organizations', '0019_organisationpublication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationpublication',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
