# Generated by Django 3.2.15 on 2022-12-28 18:04

import django.core.validators
from django.db import migrations, models
import modelcluster.fields
import rrap.organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_publicationtype'),
        ('organizations', '0021_auto_20221228_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationpublication',
            name='pub_types',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='publications', to='core.PublicationType', verbose_name='Publication type'),
        ),
        migrations.AlterField(
            model_name='organisationpublication',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, default=2022, null=True, validators=[django.core.validators.MinValueValidator(1980), rrap.organizations.models.max_value_current_year], verbose_name='Year published'),
        ),
    ]
