# Generated by Django 3.2.15 on 2022-12-28 18:50

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_publicationtype'),
        ('organizations', '0022_auto_20221228_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationpublication',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_publications', to='organizations.organisationpage'),
        ),
        migrations.AlterField(
            model_name='organisationpublication',
            name='pub_types',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='org_publications', to='core.PublicationType', verbose_name='Publication type'),
        ),
    ]
