# Generated by Django 3.2.15 on 2022-12-28 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('organizations', '0023_auto_20221228_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationpublication',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
