# Generated by Django 3.2.15 on 2023-01-03 09:20

import django.core.validators
from django.db import migrations, models
import rrap.organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_organisationindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityreach',
            name='period',
            field=models.PositiveSmallIntegerField(blank=True, default=2023, help_text='Enter year of record', null=True, validators=[django.core.validators.MinValueValidator(2000), rrap.organizations.models.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='organisationpublication',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, default=2023, null=True, validators=[django.core.validators.MinValueValidator(1980), rrap.organizations.models.max_value_current_year], verbose_name='Year published'),
        ),
        migrations.AlterField(
            model_name='violenceentry',
            name='period',
            field=models.PositiveSmallIntegerField(blank=True, default=2023, help_text='Enter year of record', null=True, validators=[django.core.validators.MinValueValidator(2000), rrap.organizations.models.max_value_current_year]),
        ),
    ]
