# Generated by Django 3.2.15 on 2023-01-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0026_auto_20230103_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationpage',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
