# Generated by Django 3.2.15 on 2023-01-09 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20221231_1221'),
        ('organizations', '0027_alter_organisationpage_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityreach',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_reach', to='core.keypopulation'),
        ),
    ]
