# Generated by Django 3.2.15 on 2023-03-02 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0028_alter_communityreach_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGBTQOrganisation',
            fields=[
                ('organisationpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.organisationpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('organizations.organisationpage',),
        ),
        migrations.CreateModel(
            name='PWUIDSOrganisation',
            fields=[
                ('organisationpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.organisationpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('organizations.organisationpage',),
        ),
        migrations.CreateModel(
            name='SexWorkOrganisation',
            fields=[
                ('organisationpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.organisationpage')),
                ('age', models.CharField(blank=True, choices=[('', 'Choose one'), ('15-19', '15-19 years'), ('20-24', '20-24 years'), ('25-29', '25-29 years'), ('30-34', '30-34 years'), ('35-39', '35-39 years'), ('40-44', '40-44 years'), ('45-49', '45-49 years'), ('50-54', '50-54 years'), ('55-59', '55-59 years'), ('60-64', '60-64 years'), ('65-69', '65-69 years'), ('70-74', '70-74 years'), ('75-79', '75-79 years'), ('80+', '80 years and above')], help_text='Select range that applies', max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('', 'Choose one'), ('Trans', 'Transgender sex workers'), ('LGB', 'LGB sex workers'), ('Gay', 'Gay sex workers'), ('MBisexual', 'Male bisexual sex workers'), ('FBisexual', 'Female bisexual sex workers')], max_length=10)),
                ('sexwork_type', models.CharField(blank=True, choices=[('', 'Choose one'), ('Street', 'Street-based'), ('Brothel', 'Brothel-based'), ('Escort', 'Escort work')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('organizations.organisationpage',),
        ),
        migrations.RemoveField(
            model_name='organisationpage',
            name='org_type',
        ),
        migrations.AddField(
            model_name='organisationpage',
            name='funding_sources',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('donor', 'Donor'), ('government', 'Government'), ('other', 'Other')], max_length=20, verbose_name='Funding sources'),
        ),
    ]
