# Generated by Django 3.2.15 on 2023-03-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0029_auto_20230302_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationpage',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='organisationpage',
            name='topics',
        ),
        migrations.AddField(
            model_name='organisationpage',
            name='needs_priorities',
            field=models.TextField(blank=True, help_text="What are the organisation's needs and priorities? Max 1000 characters", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='organisationpage',
            name='support_pwds',
            field=models.BooleanField(blank=True, default=True, help_text='Does the organisation actively support Persons with Disability(PWDs)?'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
