# Generated by Django 3.2.15 on 2023-03-02 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import rrap.organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_pwuidservice_pwuidviolation'),
        ('organizations', '0032_auto_20230302_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwuidsorganisation',
            name='communities',
        ),
        migrations.AlterField(
            model_name='pwuidsorganisation',
            name='services',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='pwuid_organisations', to='core.PWUIDService'),
        ),
        migrations.CreateModel(
            name='PWUIDViolenceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('occurences', models.PositiveSmallIntegerField(blank=True, default=0, help_text='How many violations of this nature did you deal with?', null=True)),
                ('period', models.PositiveSmallIntegerField(blank=True, default=2023, help_text='Enter year of record', null=True, validators=[django.core.validators.MinValueValidator(2000), rrap.organizations.models.max_value_current_year])),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pwuid_violations', to='organizations.pwuidsorganisation')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pwuidviolation')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
