# Generated by Django 3.2.15 on 2023-03-02 12:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import rrap.organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0033_auto_20230302_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWUIDSCommunityReach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('reach', models.PositiveSmallIntegerField(blank=True, default=0, help_text='How many people did you reach?', null=True)),
                ('period', models.PositiveSmallIntegerField(blank=True, default=2023, help_text='Enter year of record', null=True, validators=[django.core.validators.MinValueValidator(2000), rrap.organizations.models.max_value_current_year])),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pwuid_reach', to='organizations.pwuidsorganisation')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
