# Generated by Django 3.2.15 on 2023-03-06 11:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20230306_1441'),
        ('organizations', '0034_pwuidscommunityreach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityreach',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgbtq_comm_reach', to='core.lgbtqkeypopulation'),
        ),
        migrations.AlterField(
            model_name='communityreach',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgbtq_reach', to='organizations.lgbtqorganisation'),
        ),
        migrations.AlterField(
            model_name='lgbtqorganisation',
            name='communities',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='lgbtq_organisations', to='core.LGBTQKeyPopulation'),
        ),
        migrations.AlterField(
            model_name='lgbtqorganisation',
            name='services',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='lgbtq_organisations', to='core.LGBTQService'),
        ),
        migrations.AlterField(
            model_name='violenceentry',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgbtq_violations', to='organizations.lgbtqorganisation'),
        ),
        migrations.AlterField(
            model_name='violenceentry',
            name='violation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lgbtqviolation'),
        ),
    ]
