# Generated by Django 3.2.15 on 2023-03-06 11:55

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0035_auto_20230306_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityreach',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reach', to='organizations.lgbtqorganisation'),
        ),
        migrations.AlterField(
            model_name='pwuidscommunityreach',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reach', to='organizations.pwuidsorganisation'),
        ),
        migrations.AlterField(
            model_name='pwuidviolenceentry',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='organizations.pwuidsorganisation'),
        ),
        migrations.AlterField(
            model_name='swcommunityreach',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reach', to='organizations.sexworkorganisation'),
        ),
        migrations.AlterField(
            model_name='swviolenceentry',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='organizations.sexworkorganisation'),
        ),
        migrations.AlterField(
            model_name='violenceentry',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='organizations.lgbtqorganisation'),
        ),
    ]
