# Generated by Django 3.2.15 on 2023-03-06 12:06

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20230306_1441'),
        ('organizations', '0036_auto_20230306_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwuidviolenceentry',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pwuidviolenceentry',
            name='violation',
        ),
        migrations.RemoveField(
            model_name='swcommunityreach',
            name='community',
        ),
        migrations.RemoveField(
            model_name='swcommunityreach',
            name='page',
        ),
        migrations.RemoveField(
            model_name='swviolenceentry',
            name='page',
        ),
        migrations.RemoveField(
            model_name='swviolenceentry',
            name='violation',
        ),
        migrations.AlterField(
            model_name='communityreach',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.keypopulation'),
        ),
        migrations.AlterField(
            model_name='communityreach',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reach', to='organizations.organisationpage'),
        ),
        migrations.AlterField(
            model_name='lgbtqorganisation',
            name='communities',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='lgbtq_organisations', to='core.KeyPopulation'),
        ),
        migrations.AlterField(
            model_name='lgbtqorganisation',
            name='services',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='lgbtq_organisations', to='core.Service'),
        ),
        migrations.AlterField(
            model_name='pwuidsorganisation',
            name='services',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='pwuid_organisations', to='core.Service'),
        ),
        migrations.AlterField(
            model_name='sexworkorganisation',
            name='communities',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='sw_organisations', to='core.KeyPopulation'),
        ),
        migrations.AlterField(
            model_name='sexworkorganisation',
            name='services',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='sw_organisations', to='core.Service'),
        ),
        migrations.AlterField(
            model_name='violenceentry',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='organizations.organisationpage'),
        ),
        migrations.AlterField(
            model_name='violenceentry',
            name='violation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.violation'),
        ),
        migrations.DeleteModel(
            name='PWUIDSCommunityReach',
        ),
        migrations.DeleteModel(
            name='PWUIDViolenceEntry',
        ),
        migrations.DeleteModel(
            name='SWCommunityReach',
        ),
        migrations.DeleteModel(
            name='SWViolenceEntry',
        ),
    ]
