# Generated by Django 3.2.15 on 2023-03-06 18:32

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20230306_1441'),
        ('organizations', '0037_auto_20230306_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lgbtqorganisation',
            name='communities',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='lgbtq_organisations', to='core.LGBTQKeyPopulation'),
        ),
        migrations.AlterField(
            model_name='lgbtqorganisation',
            name='services',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='lgbtq_organisations', to='core.LGBTQService'),
        ),
        migrations.AlterField(
            model_name='pwuidsorganisation',
            name='services',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='pwuid_organisations', to='core.PWUIDService'),
        ),
        migrations.AlterField(
            model_name='sexworkorganisation',
            name='communities',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='sw_organisations', to='core.SWKeyPopulation'),
        ),
        migrations.AlterField(
            model_name='sexworkorganisation',
            name='services',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='sw_organisations', to='core.SWService'),
        ),
    ]
