# Generated by Django 3.2.15 on 2023-03-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0039_auto_20230306_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationpage',
            name='org_type',
            field=models.CharField(blank=True, choices=[('lgbtqorganisation', 'LGBTQ organisation'), ('sexworkorganisation', 'Sex workers organisation'), ('pwuidsorganisation', 'PWUIDs organisation')], max_length=30),
        ),
    ]
